### ISSUE TITLE
Explain the basis for last sync version selection in comment

### ISSUE THREAD

**Issue by JatinSanghvi** [Azure/azure-functions-sql-extension#306]
This issue tracks the fix to address the code review comment in #226.

Please add info about why this is done to the comment - we want to be able to know why unintuitive stuff like this was done without having to dig up the design doc for everything.

_Originally posted by @Charles-Gagnon in https://github.com/Azure/azure-functions-sql-extension/pull/226#discussion_r931507585_

**Comment by AmeyaRele** [comment]
Read up on this in the design doc and this is what I understand for the decision of new last sync version.

- Since the batch of changes are acquired in ascending order. With multiple version numbers in the batch, the other changes with version numbers that are below the highest version number should either be already processed or being leased by other workers, which is why last sync version is updated to second highest version number.
- In the query where the last sync version is actually updated in the GlobalState Table it checks if there are any unprocessed changes with version numbers lower than new last sync version. If there are none, every change with version number <= new last sync version is cleared from the Leases Table.
- It is ensured that a worker lagging behind won't update the last sync version to a lower version due to condition of updating only when `@current_last_sync_version < {newLastSyncVersion}`.

Was trying to think of scenarios where this might fail, but seems good enough to me.
Will create a PR adding comments for it.
