### ISSUE TITLE
Support output binding for auto-incremented primary key

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-sql-extension#37]
Failed to add records using Output Binding to a table with auto-incrementing id, which is commonly used in SQL DB.

It's just an idea, but it might be a solution if we can tell the Binding side that the key is auto-incremented by adding the `DatabaseGenerated` attribute to the property.

### Repro code

**Table definition**

```sql
CREATE TABLE [dbo].[TodoItems](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](255) NOT NULL,
	[Body] [nvarchar](max) NOT NULL,
	CONSTRAINT [PK_TodoItems] PRIMARY KEY CLUSTERED ([Id] ASC)
)
```

**Function code**

```csharp
public class TodoItem
{
    // Temporary comment out
    //public int Id { get; set; }
    public string Title { get; set; }
    public string Body { get; set; }
}

public class Function1
{
    [FunctionName("Function1")]
    public async Task<IActionResult> Run(
        [HttpTrigger(AuthorizationLevel.Function, "get")] HttpRequest req,
        [Sql("dbo.TodoItems", ConnectionStringSetting = "SqlConnection")] IAsyncCollector<TodoItem> items,
        ILogger log)
    {
        await items.AddAsync(new TodoItem
        {
            Title = "foo",
            Body = "bar"
        });

        return new OkResult();
    }
}
```

### Expected

`Id` value is generated in an auto-increment and the record is successfully added to the DB.

### Actual

I tried every possible pattern, but the only way I could find was to disable the auto-incremented `Id`.

**Comment out the `Id` property**

> System.Private.CoreLib: Exception while executing function: Function1. Microsoft.Azure.WebJobs.Host: Error while handling parameter items after function returned:. SqlBinding: All primary keys for SQL table 'TodoItems' and schema ''dbo'' need to be found in 'FunctionApp25.TodoItem.' Missing primary keys: [Id].

**Uncommenting the `Id` property**

> System.Private.CoreLib: Exception while executing function: Function1. Microsoft.Azure.WebJobs.Host: Error while handling parameter items after function returned:. Core Microsoft SqlClient Data Provider: Cannot update identity column 'Id'.

**Comment by mark-quickel** [comment]
Confirming this issue as well today after not being able to find a workaround for these identity fields. Auto-incremented identity fields are a common pattern and should be minimally updated as "not supported" in the documentation.

**Comment by Charles-Gagnon** [comment]
@lucyzhang929 I'll take a look at this one - seems straightforward enough (I had actually noticed this in some early testing but it slipped my mind to look into it further...) and the use case is definitely common.

**Comment by Charles-Gagnon** [comment]
@shibayan @mark-quickel I wanted to get your feedback on how you see this being used. Because right now we generate a merge statement for the upserts that requires checking whether a row already "exists" - and this is done by comparing primary keys. So that isn't going to work if there's an identity column (and one isn't specified in the object).

Would you rather : 

1. Have it always insert if an identity column is detected but isn't included in the mapping object
2. Have a parameter in the sql binding attribute to tell us whether to use a merge statement (current behavior) or always insert
3. Some other option?

**Comment by Charles-Gagnon** [comment]
We just released a new version of the extension that has the fix for identity columns in it - try it out when you get a chance and let us know if there's any other improvements we should make! Thank you for your patience.

https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Sql/0.1.207-preview
