### ISSUE TITLE
Use local extension package for OOP tests

### ISSUE THREAD

**Issue by MaddyDev** [Azure/azure-functions-sql-extension#623]
Currently the tests pull the sql extension from nuget to test, update this to pick up the local package. This will mean the tests need to know how to load the local version of the package (which likely means a nuget.config pointing to the bin folder as a source)

**Comment by Charles-Gagnon** [comment]
@MaddyDev I'm reopening this currently isn't working as intended

1. Locally I can't even build the samples project from a fresh machine. Running dotnet build from the I get an error like

```
C:\Users\chgagnon\AppData\Local\Temp\ituxhlhb.goj\WorkerExtensions.csproj : error NU1102: Unable to find package Micros
oft.Azure.WebJobs.Extensions.Sql with version (>= 99.99.99)
```

This is because an OOP function will cause a special "WorkerExtensions.csproj" project to be created and built from a temp directory which means it doesn't pick up the custom nuget.config we have in our repo. 

A workaround is to run `dotnet nuget add source` (from a directory outside the project) and then point it to the local dir. But then this still has a problem where Nuget caches the package - and so that means any future builds won't pick up the latest changes and instead have whatever that first version of the local package it got was.

https://github.com/Azure/azure-functions-dotnet-worker/issues/550 is already open for tracking allowing a custom nuget.config, although that still doesn't solve the second problem I had. For that we should probably look into something like suggested here : https://stackoverflow.com/a/69814363 where we clear the Nuget cache for our 99.99.99 package every time we build. 

2. In the pipelines it builds but that's because we specify the package version as [$(versionMajor).*-*](https://github.com/Azure/azure-functions-sql-extension/blob/main/builds/azure-pipelines/build-release.yml#L22), which means that it'll pick up whatever the latest 1.* version is. 

This one is a bit trickier since we need to keep it as 1.* for the actual package we publish, but we want to use a DIFFERENT version when we run the tests. So my thought here is that we're going to need to do something like this : 

- First build the worker project with the 99.99.99 version and run the tests
- After that change the version to the 1.* version and then re-build, and publish the package generated from that

**Comment by Charles-Gagnon** [comment]
@MaddyDev I'm currently taking a look at it since I had context on the issue and fxing it is important for the bundle verification. So you can keep working on your other tasks for the time being - I'll let you know if I need any help here.
