### ISSUE TITLE
How to avoid multiple state rows and leases for the same table, same function?

### ISSUE THREAD

**Issue by denious** [Azure/azure-functions-sql-extension#724]
We have 4 functions in total, one per table, and are currently in the development DB, playing with code, running and stopping the functions app, making changes, and we noticed multiple state rows and lease tables being created for the same table and the same function, up to 6 for a single table, see below. 

1. What is causing this behavior?
2. Will these state rows and lease tables be automatically cleaned up?
3. How do we avoid this behavior?

![image](https://user-images.githubusercontent.com/7120854/224781968-8b576d19-aa69-408c-bbed-9ce223e3c1ae.png)

![image](https://user-images.githubusercontent.com/7120854/224783572-5865e6d7-e43f-495f-87a0-4aeca190b416.png)

**Comment by Charles-Gagnon** [comment]
Initial answer to your questions:

1. There should be a single leases table made for each instance of the function and the table it's monitoring. The format of the table name is `az_func.Leases_<FunctionId>_<TableID>`

See https://github.com/Azure/azure-functions-sql-extension/blob/main/docs/BindingsOverview.md#az_funcleases_more more details about that

So if the function ID or table ID changes then a new leases table will be generated. Are you changing the name of the function with the trigger on it? As long as or the function assembly name doesn't change it should be using the same ID

2. Not currently, we have an issue tracking figuring this out though so it's something on our radar https://github.com/Azure/azure-functions-sql-extension/issues/681

3. As long as the table ID & function info (assembly + name) doesn't change then it shouldn't be doing this. Once we get more information we can determine if this is expected behavior and figure out a solution from there.

**Comment by nicdillon** [comment]
@Charles-Gagnon We have changed the function names at least once. That being the cause makes sense looking at the LastSyncVersion numbers (4 with relatively high numbers, the rest much lower).  If that is the cause of the additional tables being created, are we good to drop the lease tables showing old version numbers? Is there a way to verify the function ID to ensure we don't remove the wrong tables?

**Comment by Charles-Gagnon** [comment]
Yup, you're good to drop the old tables. And you can look at the function logs to see the current leases table being used then delete the rest - unfortunately there isn't an easier way since reverse engineering the ID generation isn't straightforward. 

Code in case you're interested : https://github.com/Azure/azure-functions-sql-extension/blob/main/src/TriggerBinding/SqlTriggerBinding.cs#L98

**Comment by nicdillon** [comment]
@Charles-Gagnon Understood. Thank you!
