### ISSUE TITLE
StoredProcedure using FOR JSON AUTO is not parsed as JSON

### ISSUE THREAD

**Issue by maersk96** [Azure/azure-functions-sql-extension#774]
I am trying to query a Master table with nested array from Details table. I am using FOR JSON AUTO to convert the Details-records to an array property on the Master record.

The returned output is unparsed JSON like this:

![image](https://user-images.githubusercontent.com/7141352/228472085-26650c8e-e723-4773-9871-2f4856328c4c.png)

And this is the relevant SQL in the stored procedure:

![image](https://user-images.githubusercontent.com/7141352/228472225-21ad891f-1807-4145-8084-7e238dae3460.png)

I would expect the output to be parsed JSON.

Am i missing a setting somewhere? I know in tedious there is a parseJSON option.

**Comment by Charles-Gagnon** [comment]
So the issue here is that the inner JSON (the "versions" field) is coming back as an escaped string from the SQL query itself, which the JSON deserializer can't automatically handle.

I'm not sure this is something we'd be able to fix on our end given that - we wouldn't be able to tell when a string is a JSON string versus just some other normal string.

But a workaround you could do is to manually convert the field after getting it from the server. So an example in C# using a property getter would be 

![image](https://user-images.githubusercontent.com/28519865/228628112-857d7cd6-621f-4f2d-80ca-3f1add4a5dcc.png)

Where inner is the JSON field from the query, e.g. 

`SELECT *, (SELECT * FROM PRODUCTS FOR JSON AUTO) AS [Inner] FROM Products`

Would you be able to do something like that instead?

**Comment by maersk96** [comment]
Yeah, that’s a manageable workaround. Thank you.
The tedious parseJSON option is probably applied on the javascript/client-side aswell.
