### ISSUE TITLE
Is it possible to use the SQL trigger from an on-premises SQL server?

### ISSUE THREAD

**Issue by TWolversonReply** [Azure/azure-functions-sql-extension#915]
I have just learned of this binding and it has the potential to be very useful for us. We often work with hybrid scenarios where the data source is an on-premises SQL server. Is it possible to target an on-premises SQL server using the SQL function trigger, or does it rely on features that only Azure SQL has? I would be open to a number of options for connectivity potentially including self-hosting the functions runtime in the data centre, peering to the on-premises network over a VPN gateway, or configuring a hybrid connection. I can understand if this scenario is not directly supported, but would appreciate some guidance as to whether it is fundamentally possible and if so, what I would need to do to enable it.

**Comment by Charles-Gagnon** [comment]
The extension only needs a SqlClient connection using the connection string you give it, so as long as you have the networking set up it should be able to connect to an on-premise server just fine (although that isn't a scenario we've tested ourselves AFAIK)

Here's some stuff I found that may be useful for getting that working : 
https://learn.microsoft.com/en-us/answers/questions/169314/azure-function-app-connect-to-on-prem-sql
https://learn.microsoft.com/en-us/azure/azure-functions/functions-networking-options?tabs=azure-cli#matrix-of-networking-features

Let us know if you run into issues and we'd be happy to try and help figure out a solution!

I'll close this for now since this should be working, and if there are problems we can reopen and investigate further.
